const express = require("express");
const dotenv = require("dotenv");
const path = require("path");
const fs = require("fs");
const { runTask, runRealTask } = require("./services/taskRunner");
const { startTelegramBot, sendTelegramTaskUpdate } = require("./services/telegramBot");
const { readEnvFile, upsertEnvKey, ensureEnvFileExists } = require("./services/dotEnvFile");
const { getLastChatIdFromUpdates } = require("./services/telegramClient");
const {
  recordTelegramEvent,
  getTelegramDebugSnapshot,
  syncTelegramDebugEnv,
} = require("./services/telegramDebug");

dotenv.config();

const app = express();
app.use(express.json());

const PORT = Number(process.env.PORT || 4100);
const BRIDGE_MODE = process.env.BRIDGE_MODE === "real" ? "real" : "mock";
const ENV_FILE_PATH = path.join(__dirname, ".env");

let telegramRuntime = { stop() {}, enabled: false };

function getTelegramEnv() {
  return {
    token: String(process.env.TELEGRAM_BOT_TOKEN || "").trim(),
    chatId: String(process.env.TELEGRAM_ALLOWED_CHAT_ID || "").trim(),
  };
}

function reloadProcessEnvFromFile() {
  if (fs.existsSync(ENV_FILE_PATH)) {
    dotenv.config({ path: ENV_FILE_PATH, override: true });
  }
}

app.get("/telegram-debug", (req, res) => {
  reloadProcessEnvFromFile();
  let telegramEnabled = true;
  let allowedChatId = process.env.TELEGRAM_ALLOWED_CHAT_ID || null;
  if (typeof allowedChatId === "string" && allowedChatId.trim() === "") {
    allowedChatId = null;
  }
  let lastTelegramEvent = null;
  let lastTelegramError = null;
  let lastTelegramMessageMeta = null;
  try {
    const { token, chatId } = getTelegramEnv();
    telegramEnabled = Boolean(token && chatId);
    allowedChatId = chatId || null;
    syncTelegramDebugEnv({ telegramEnabled, allowedChatId });
    const snap = getTelegramDebugSnapshot();
    lastTelegramEvent = snap.lastTelegramEvent != null ? snap.lastTelegramEvent : null;
    lastTelegramError = snap.lastTelegramError != null ? snap.lastTelegramError : null;
    lastTelegramMessageMeta =
      snap.lastTelegramMessageMeta != null && typeof snap.lastTelegramMessageMeta === "object"
        ? snap.lastTelegramMessageMeta
        : null;
  } catch (_e) {
    // остаются заглушки выше
  }
  res.json({
    telegramEnabled,
    allowedChatId,
    lastTelegramEvent,
    lastTelegramError,
    lastTelegramMessageMeta,
  });
});
console.log("TELEGRAM DEBUG ROUTE ACTIVE");

function stopTelegramRuntime() {
  try {
    telegramRuntime.stop();
  } catch (_e) {
    // ignore
  }
  telegramRuntime = { stop() {}, enabled: false };
}

function startTelegramRuntimeFromProcessEnv() {
  const { token, chatId } = getTelegramEnv();
  if (!token) {
    return;
  }
  stopTelegramRuntime();
  telegramRuntime = startTelegramBot({
    token,
    allowedChatId: chatId,
    logger: console,
    onQuickTask: async (text, meta) => {
      const quickRun = await runQuickTaskFromText(text, {
        sourceLabel: "telegram bot",
        source: "telegram",
        telegramChatId: meta && meta.chatId != null ? String(meta.chatId) : null,
        telegramMessageId: meta && meta.messageId != null ? meta.messageId : null,
        triggerLog: "telegram task triggered",
        planEventMessage: "Auto-plan generated by telegram bot",
        executionEventMessage: "Execution started from telegram bot",
      });
      if (!quickRun.ok || !quickRun.task) {
        return `Ошибка запуска задачи: ${quickRun.error || "unknown error"}`;
      }
      const t = quickRun.task;
      recordTelegramEvent(
        `task created from telegram id=${t.id} source=${t.source} telegramChatId=${t.telegramChatId} telegramMessageId=${t.telegramMessageId ?? "null"}`
      );
      return formatTelegramTaskLaunch(quickRun.task);
    },
    onStatus: async (taskIdRaw) => {
      const taskId = String(taskIdRaw || "").trim();
      if (!taskId) {
        return "Укажите taskId: /status <taskId>";
      }
      const task = tasks.get(taskId);
      if (!task) {
        return `Task not found: ${taskId}`;
      }
      return formatTelegramTaskStatus(task);
    },
    onLast: async () => {
      const task = getLatestTask();
      if (!task) {
        return "Задач пока нет";
      }
      return formatTelegramLastTask(task);
    },
    onHelp: async () => telegramHelpText(),
  });
}

async function tryAutoFillTelegramChatIdFromUpdates() {
  reloadProcessEnvFromFile();
  const { token, chatId } = getTelegramEnv();
  if (!token || chatId) {
    return { updated: false, reason: chatId ? "chat_already_set" : "no_token" };
  }
  const result = await getLastChatIdFromUpdates(token);
  if (!result.ok || !result.chatId) {
    return { updated: false, probe: result };
  }
  ensureEnvFileExists(ENV_FILE_PATH);
  upsertEnvKey(ENV_FILE_PATH, "TELEGRAM_ALLOWED_CHAT_ID", result.chatId);
  reloadProcessEnvFromFile();
  console.log(`telegram: auto-filled TELEGRAM_ALLOWED_CHAT_ID from getUpdates`);
  return { updated: true, chatId: result.chatId };
}

app.get("/telegram-setup", (_req, res) => {
  return res.sendFile(path.join(__dirname, "public", "telegram-setup.html"));
});

app.get("/api/telegram-status", (_req, res) => {
  reloadProcessEnvFromFile();
  const { token, chatId } = getTelegramEnv();
  const disk = fs.existsSync(ENV_FILE_PATH) ? readEnvFile(ENV_FILE_PATH).map : {};
  const hasToken = Boolean(token || disk.TELEGRAM_BOT_TOKEN);
  const hasChatId = Boolean(String(chatId || disk.TELEGRAM_ALLOWED_CHAT_ID || "").trim());
  res.json({
    ok: true,
    envFileExists: fs.existsSync(ENV_FILE_PATH),
    hasToken,
    hasChatId,
    needsChatProbe: Boolean(hasToken && !hasChatId),
    chatId: String(chatId || disk.TELEGRAM_ALLOWED_CHAT_ID || "").trim() || null,
    telegramEnabled: Boolean(getTelegramEnv().token && getTelegramEnv().chatId),
    runtimePolling: Boolean(telegramRuntime && telegramRuntime.enabled === true),
  });
});

app.post("/api/telegram-config", (req, res) => {
  const body = req.body || {};
  const tokenIn = typeof body.token === "string" ? body.token.trim() : "";
  const chatIn = typeof body.chatId === "string" ? body.chatId.trim() : "";

  if (!tokenIn && !chatIn) {
    return res.status(400).json({ ok: false, error: "Укажите token и/или chat id" });
  }

  ensureEnvFileExists(ENV_FILE_PATH);
  if (tokenIn) {
    upsertEnvKey(ENV_FILE_PATH, "TELEGRAM_BOT_TOKEN", tokenIn);
  }
  if (chatIn) {
    upsertEnvKey(ENV_FILE_PATH, "TELEGRAM_ALLOWED_CHAT_ID", chatIn);
  }

  reloadProcessEnvFromFile();
  const { token, chatId } = getTelegramEnv();
  if (!token) {
    return res.status(400).json({ ok: false, error: "Сначала сохраните TELEGRAM_BOT_TOKEN" });
  }

  syncTelegramDebugEnv({
    telegramEnabled: Boolean(token && chatId),
    allowedChatId: chatId || null,
  });
  startTelegramRuntimeFromProcessEnv();
  return res.json({
    ok: true,
    saved: true,
    telegramEnabled: Boolean(token && chatId),
    chatId: chatId || null,
    message: token && chatId ? "Telegram перезапущен без перезапуска bridge" : "Сохранено. Укажите chat id или нажмите «Проверить сообщения».",
  });
});

app.post("/api/telegram-probe-updates", async (req, res) => {
  const body = req.body || {};
  reloadProcessEnvFromFile();
  const tokenFromBody = typeof body.token === "string" ? body.token.trim() : "";
  const { token: tokenFromEnv } = getTelegramEnv();
  const token = tokenFromBody || tokenFromEnv;
  if (!token) {
    return res.status(400).json({ ok: false, error: "token missing" });
  }
  const probe = await getLastChatIdFromUpdates(token);
  if (!probe.ok) {
    return res.status(400).json({ ok: false, error: probe.error || "getUpdates failed" });
  }
  if (!probe.chatId) {
    return res.json({
      ok: true,
      found: false,
      message: "Нет входящих обновлений. Напишите боту в Telegram и повторите.",
    });
  }
  ensureEnvFileExists(ENV_FILE_PATH);
  upsertEnvKey(ENV_FILE_PATH, "TELEGRAM_ALLOWED_CHAT_ID", probe.chatId);
  reloadProcessEnvFromFile();
  const { token: t2, chatId: c2 } = getTelegramEnv();
  syncTelegramDebugEnv({
    telegramEnabled: Boolean(t2 && c2),
    allowedChatId: c2 || null,
  });
  startTelegramRuntimeFromProcessEnv();
  return res.json({
    ok: true,
    found: true,
    chatId: probe.chatId,
    saved: true,
    message: "chat_id сохранён в .env, Telegram перезапущен",
  });
});

app.use(express.static(path.join(__dirname, "public")));

// In-memory task storage (temporary, resets on server restart).
const tasks = new Map();
let seq = 1;

const ALLOWED_STATUSES = new Set(["queued", "running", "done", "failed"]);
const ALLOWED_AGENT_STATUSES = new Set([
  "pending",
  "submitted",
  "running",
  "finished",
  "failed",
]);
const ALLOWED_REVIEW_STATUSES = new Set(["pending", "approved", "rejected"]);
const ALLOWED_LIFECYCLE_STAGES = new Set([
  "created",
  "planned",
  "waiting_user",
  "ready",
  "executing",
  "reported",
  "under_review",
  "revision_requested",
  "completed",
  "failed",
]);

function nowIso() {
  return new Date().toISOString();
}

function makeId() {
  const id = `task_${Date.now()}_${seq}`;
  seq += 1;
  return id;
}

function pushLog(task, message) {
  task.logs.push({
    at: nowIso(),
    message: String(message || ""),
  });
}

function addHistoryEvent(task, type, message, meta = {}) {
  if (!Array.isArray(task.history)) {
    task.history = [];
  }
  task.history.push({
    timestamp: nowIso(),
    type,
    message: String(message || ""),
    meta: isPlainObject(meta) ? meta : {},
  });
}

function hasExecutionIssues(task) {
  if (task.status === "failed" || task.agentStatus === "failed") return true;
  if (!isPlainObject(task.result)) return true;
  return Object.keys(task.result).length === 0;
}

function sanitizeTask(task) {
  return {
    id: task.id,
    title: task.title,
    prompt: task.prompt,
    source: task.source,
    telegramChatId: task.telegramChatId,
    telegramMessageId: task.telegramMessageId,
    goal: task.goal,
    targetPaths: task.targetPaths,
    constraints: task.constraints,
    acceptanceChecks: task.acceptanceChecks,
    context: task.context,
    plan: task.plan,
    risks: task.risks,
    questions: task.questions,
    needsUserInput: task.needsUserInput,
    status: task.status,
    executionMode: task.executionMode,
    externalTaskId: task.externalTaskId,
    agentStatus: task.agentStatus,
    reviewStatus: task.reviewStatus,
    report: task.report,
    reviewNotes: task.reviewNotes,
    controllerDecision: task.controllerDecision,
    lifecycleStage: task.lifecycleStage,
    history: task.history,
    lastAction: task.lastAction,
    archived: task.archived,
    revisionCount: task.revisionCount,
    revisions: task.revisions,
    latestRevision: task.latestRevision,
    previousResults: task.previousResults,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt,
    result: task.result,
    logs: task.logs,
  };
}

function buildRevisionStateSummary(task) {
  return {
    revisionCount:
      typeof task.revisionCount === "number" ? task.revisionCount : 0,
    latestRevision: isPlainObject(task.latestRevision) ? task.latestRevision : null,
    previousResultsCount: Array.isArray(task.previousResults)
      ? task.previousResults.length
      : 0,
  };
}

function buildTaskSummary(task) {
  const safeResult = isPlainObject(task.result) ? task.result : {};
  const safeReport = isPlainObject(task.report) ? task.report : null;

  const revisionState = buildRevisionStateSummary(task);

  return {
    id: task.id,
    goal: task.goal,
    status: task.status,
    agentStatus: task.agentStatus,
    reviewStatus: task.reviewStatus,
    controllerDecision: task.controllerDecision,
    changedFiles: Array.isArray(safeResult.changedFiles) ? safeResult.changedFiles : [],
    diffSummary:
      typeof safeResult.diffSummary === "string" ? safeResult.diffSummary : "",
    checks: Array.isArray(safeResult.checks) ? safeResult.checks : [],
    lastReport: safeReport,
    lastLogs: Array.isArray(task.logs) ? task.logs.slice(-5) : [],
    lifecycleStage: task.lifecycleStage,
    lastAction: task.lastAction,
    archived: Boolean(task.archived),
    lastHistoryEvents: Array.isArray(task.history) ? task.history.slice(-5) : [],
    revisionCount: revisionState.revisionCount,
    latestRevision: revisionState.latestRevision,
    previousResultsCount: revisionState.previousResultsCount,
  };
}

function applyControllerReviewDecision(task, decision, note, nextAction) {
  task.controllerDecision = decision;
  task.reviewNotes = {
    note: typeof note === "string" ? note : "",
    nextAction: typeof nextAction === "string" ? nextAction : "",
    at: nowIso(),
  };

  if (decision === "approve") {
    task.reviewStatus = "approved";
    task.lifecycleStage = "completed";
    task.lastAction = "controller_reviewed";
    addHistoryEvent(task, "task_completed", "Controller approved task");
  } else if (decision === "reject") {
    task.reviewStatus = "rejected";
    task.lifecycleStage = "failed";
    task.lastAction = "controller_reviewed";
    addHistoryEvent(task, "task_failed", "Controller rejected task");
  } else {
    task.reviewStatus = "pending";
    task.lifecycleStage = "under_review";
    task.lastAction = "controller_reviewed";
  }

  pushLog(
    task,
    `controller-review: ${decision}${
      note ? ` | note: ${note}` : ""
    }${nextAction ? ` | nextAction: ${nextAction}` : ""}`
  );
  addHistoryEvent(task, "controller_reviewed", "Controller review decision saved", {
    decision,
    note: typeof note === "string" ? note : "",
    nextAction: typeof nextAction === "string" ? nextAction : "",
  });

  if (
    decision === "revise" &&
    task.source === "telegram" &&
    !task._suppressTelegramReviseFromController
  ) {
    void sendTelegramTaskUpdate(task, "revise", { logger: console }).catch(() => {});
  }
}

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isStringArray(value) {
  return Array.isArray(value) && value.every((item) => typeof item === "string");
}

function makeShortTitle(goal) {
  const clean = String(goal || "").trim().replace(/\s+/g, " ");
  if (clean.length <= 72) return clean;
  return `${clean.slice(0, 69)}...`;
}

function buildPromptFromTaskParts({
  goal,
  targetPaths,
  constraints,
  acceptanceChecks,
  context,
}) {
  const lines = [];
  lines.push(`Goal:\n- ${goal}`);

  if (targetPaths.length > 0) {
    lines.push(
      `Target paths:\n${targetPaths.map((item) => `- ${item}`).join("\n")}`
    );
  }

  if (constraints.length > 0) {
    lines.push(
      `Constraints:\n${constraints.map((item) => `- ${item}`).join("\n")}`
    );
  }

  if (acceptanceChecks.length > 0) {
    lines.push(
      `Acceptance checks:\n${acceptanceChecks
        .map((item) => `- ${item}`)
        .join("\n")}`
    );
  }

  const contextEntries = Object.entries(context || {});
  if (contextEntries.length > 0) {
    lines.push(
      `Context:\n${contextEntries
        .map(([key, value]) => `- ${key}: ${String(value)}`)
        .join("\n")}`
    );
  }

  return lines.join("\n\n");
}

function normalizeTaskInput(body) {
  const payload = body || {};
  const hasGoal = payload.goal !== undefined;

  if (hasGoal) {
    if (typeof payload.goal !== "string" || !payload.goal.trim()) {
      return { error: "goal is required and must be a non-empty string" };
    }
  } else {
    if (
      typeof payload.title !== "string" ||
      !payload.title.trim() ||
      typeof payload.prompt !== "string" ||
      !payload.prompt.trim()
    ) {
      return {
        error:
          "Either provide new format with goal, or legacy format with title and prompt",
      };
    }
  }

  if (payload.targetPaths !== undefined && !isStringArray(payload.targetPaths)) {
    return { error: "targetPaths must be an array of strings" };
  }
  if (payload.constraints !== undefined && !isStringArray(payload.constraints)) {
    return { error: "constraints must be an array of strings" };
  }
  if (
    payload.acceptanceChecks !== undefined &&
    !isStringArray(payload.acceptanceChecks)
  ) {
    return { error: "acceptanceChecks must be an array of strings" };
  }
  if (payload.context !== undefined && !isPlainObject(payload.context)) {
    return { error: "context must be an object" };
  }

  const targetPaths = payload.targetPaths || [];
  const constraints = payload.constraints || [];
  const acceptanceChecks = payload.acceptanceChecks || [];
  const context = payload.context || {};

  if (hasGoal) {
    const goal = payload.goal.trim();
    const generatedTitle = makeShortTitle(goal);
    const generatedPrompt = buildPromptFromTaskParts({
      goal,
      targetPaths,
      constraints,
      acceptanceChecks,
      context,
    });

    return {
      normalizedTask: {
        goal,
        targetPaths,
        constraints,
        acceptanceChecks,
        context,
      },
      generatedTitle,
      generatedPrompt,
    };
  }

  // Legacy support: keep provided title/prompt and map title into goal.
  const legacyTitle = payload.title.trim();
  return {
    normalizedTask: {
      goal: legacyTitle,
      targetPaths,
      constraints,
      acceptanceChecks,
      context,
    },
    generatedTitle: legacyTitle,
    generatedPrompt: payload.prompt.trim(),
  };
}

function createBaseTaskFromParsed(parsed, options = {}) {
  const { normalizedTask, generatedTitle, generatedPrompt } = parsed;
  const sourceLabel =
    typeof options.sourceLabel === "string" && options.sourceLabel.trim()
      ? options.sourceLabel.trim()
      : "api";
  const source =
    options.source === "web" || options.source === "telegram" || options.source === "manual"
      ? options.source
      : "manual";
  const telegramChatId =
    options.telegramChatId != null && String(options.telegramChatId).trim() !== ""
      ? String(options.telegramChatId).trim()
      : null;
  const telegramMessageId =
    options.telegramMessageId != null && Number.isFinite(Number(options.telegramMessageId))
      ? Number(options.telegramMessageId)
      : null;

  const task = {
    id: makeId(),
    title: generatedTitle,
    prompt: generatedPrompt,
    source,
    telegramChatId,
    telegramMessageId,
    goal: normalizedTask.goal,
    targetPaths: normalizedTask.targetPaths,
    constraints: normalizedTask.constraints,
    acceptanceChecks: normalizedTask.acceptanceChecks,
    context: normalizedTask.context,
    plan: [],
    risks: [],
    questions: [],
    needsUserInput: false,
    status: "queued",
    executionMode: BRIDGE_MODE,
    externalTaskId: null,
    agentStatus: "pending",
    reviewStatus: "pending",
    report: null,
    reviewNotes: null,
    controllerDecision: null,
    lifecycleStage: "created",
    history: [],
    lastAction: "task_created",
    archived: false,
    revisionCount: 0,
    revisions: [],
    latestRevision: null,
    previousResults: [],
    createdAt: nowIso(),
    updatedAt: nowIso(),
    result: null,
    logs: [],
  };

  pushLog(task, "Task created and queued");
  addHistoryEvent(task, "task_created", `Task created from ${sourceLabel}`);
  tasks.set(task.id, task);
  return task;
}

async function startTaskWithRunner(task, failureContext) {
  try {
    await runTask(task, tasks);
    return { ok: true };
  } catch (error) {
    task.status = "failed";
    task.agentStatus = "failed";
    task.lifecycleStage = "failed";
    task.lastAction = "task_failed";
    task.updatedAt = nowIso();
    pushLog(task, `Task runner error: ${error.message || "unknown error"}`);
    addHistoryEvent(task, "task_failed", failureContext, {
      error: error.message || "unknown error",
    });
    tasks.set(task.id, task);
    return {
      ok: false,
      error,
    };
  }
}

async function runQuickTaskFromText(text, options = {}) {
  const goalText = typeof text === "string" ? text.trim() : "";
  if (!goalText) {
    return { ok: false, error: "Task text is required", statusCode: 400 };
  }

  const parsed = normalizeTaskInput({ goal: goalText });
  if (parsed.error) {
    return { ok: false, error: parsed.error, statusCode: 400 };
  }

  const sourceLabel =
    typeof options.sourceLabel === "string" && options.sourceLabel.trim()
      ? options.sourceLabel.trim()
      : "quick task endpoint";
  const triggerLog =
    typeof options.triggerLog === "string" && options.triggerLog.trim()
      ? options.triggerLog.trim()
      : "";
  const planEventMessage =
    typeof options.planEventMessage === "string" && options.planEventMessage.trim()
      ? options.planEventMessage.trim()
      : "Auto-plan generated by quick task flow";
  const executionEventMessage =
    typeof options.executionEventMessage === "string" && options.executionEventMessage.trim()
      ? options.executionEventMessage.trim()
      : "Execution started from quick task flow";

  const task = createBaseTaskFromParsed(parsed, {
    sourceLabel,
    source: options.source === "web" || options.source === "telegram" || options.source === "manual"
      ? options.source
      : "manual",
    telegramChatId: options.telegramChatId,
    telegramMessageId: options.telegramMessageId,
  });
  if (triggerLog) {
    pushLog(task, triggerLog);
  }

  task.plan = [
    "Понять цель и текущий контекст задачи",
    "Внести необходимые изменения в целевые места",
    "Проверить результат и подготовить краткую сводку",
  ];
  task.needsUserInput = false;
  task.agentStatus = "submitted";
  task.lifecycleStage = "ready";
  task.lastAction = "plan_received";
  pushLog(task, "plan received");
  addHistoryEvent(task, "plan_received", planEventMessage);
  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  task.status = "running";
  task.lifecycleStage = "executing";
  task.lastAction = "execution_started";
  pushLog(task, "execution started");
  addHistoryEvent(task, "execution_started", executionEventMessage);
  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  const startResult = await startTaskWithRunner(task, "Execution failed in quick task flow");
  if (!startResult.ok) {
    const t = tasks.get(task.id);
    if (t) void tryNotifyTelegramExecutionOutcome(t).catch(() => {});
  }
  return {
    ok: startResult.ok,
    error: startResult.ok ? null : startResult.error?.message || "unknown error",
    statusCode: startResult.ok ? 200 : 500,
    task,
  };
}

function getLatestTask() {
  const list = Array.from(tasks.values());
  if (list.length === 0) return null;
  list.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  return list[0] || null;
}

function toShortSummary(task) {
  if (isPlainObject(task?.result) && typeof task.result.summary === "string") {
    const value = task.result.summary.trim();
    if (value) return value;
  }
  if (task?.status === "running") return "Task accepted and running";
  if (task?.status === "queued") return "Task queued";
  if (task?.status === "failed") return "Task failed";
  return "Summary is not available yet";
}

function formatTelegramTaskLaunch(task) {
  return [
    `taskId: ${task.id}`,
    `goal: ${task.goal || task.title || "—"}`,
    `status: ${task.status || "—"}`,
    `summary: ${toShortSummary(task)}`,
  ].join("\n");
}

function formatTelegramTaskStatus(task) {
  const goal = task.goal || task.title || "—";
  const logLines = Array.isArray(task.logs)
    ? task.logs
        .slice(-3)
        .map((l) => (l && l.message ? String(l.message) : ""))
        .filter(Boolean)
    : [];
  const logsText = logLines.length ? logLines.map((l) => `  • ${l}`).join("\n") : "  —";
  return [
    `taskId: ${task.id}`,
    `goal: ${goal}`,
    `status: ${task.status || "—"}`,
    `agentStatus: ${task.agentStatus || "—"}`,
    `reviewStatus: ${task.reviewStatus || "—"}`,
    `controllerDecision: ${task.controllerDecision || "—"}`,
    `lifecycleStage: ${task.lifecycleStage || "—"}`,
    `последние 3 лога:`,
    logsText,
  ].join("\n");
}

function formatTelegramLastTask(task) {
  const res = isPlainObject(task.result) ? task.result : {};
  const summary =
    typeof res.summary === "string" && res.summary.trim() ? res.summary.trim() : "—";
  return [
    `taskId: ${task.id}`,
    `status: ${task.status || "—"}`,
    `controllerDecision: ${task.controllerDecision || "—"}`,
    `lifecycleStage: ${task.lifecycleStage || "—"}`,
    `summary: ${summary}`,
  ].join("\n");
}

async function tryNotifyTelegramExecutionOutcome(task) {
  const current = tasks.get(task.id);
  if (!current || current.source !== "telegram" || !current.telegramChatId) return;
  if (current._telegramExecutionOutcomeSent) return;
  if (current.status === "done") {
    if (!isPlainObject(current.result) || Object.keys(current.result).length === 0) return;
    current._telegramExecutionOutcomeSent = true;
    tasks.set(current.id, current);
    await sendTelegramTaskUpdate(current, "execution_done", { logger: console });
    return;
  }
  if (current.status === "failed") {
    current._telegramExecutionOutcomeSent = true;
    tasks.set(current.id, current);
    const lastLog =
      Array.isArray(current.logs) && current.logs.length
        ? String(current.logs[current.logs.length - 1].message || "")
        : "";
    await sendTelegramTaskUpdate(current, "execution_error", {
      logger: console,
      errorText: lastLog || "Задача завершилась с ошибкой",
    });
  }
}

function telegramHelpText() {
  return [
    "Отправьте обычный текст, чтобы запустить задачу.",
    "/status <taskId> — проверить статус задачи.",
    "/last — показать последнюю задачу.",
    "/help — показать эту справку.",
  ].join("\n");
}

async function requestRevisionForTask(task, reason, instructions, requestedBy) {
  task._telegramExecutionOutcomeSent = false;
  if (task.result) {
    task.previousResults = Array.isArray(task.previousResults)
      ? [...task.previousResults, task.result]
      : [task.result];
    task.result = null;
  }

  task.revisionCount = typeof task.revisionCount === "number" ? task.revisionCount + 1 : 1;
  const revision = {
    revisionId: `rev-${task.revisionCount}`,
    createdAt: nowIso(),
    reason: reason.trim(),
    instructions: instructions.trim(),
    requestedBy:
      typeof requestedBy === "string" && requestedBy.trim()
        ? requestedBy.trim()
        : "controller",
    status: "queued",
  };

  task.revisions = Array.isArray(task.revisions)
    ? [...task.revisions, revision]
    : [revision];
  task.latestRevision = revision;
  task.status = "queued";
  task.reviewStatus = "pending";
  task.controllerDecision = "revise";
  task.lifecycleStage = "revision_requested";
  task.lastAction = "revision_requested";
  task.updatedAt = nowIso();
  pushLog(task, "revision requested");
  addHistoryEvent(task, "revision_requested", "Revision requested", {
    revisionId: revision.revisionId,
    reason: revision.reason,
  });
  tasks.set(task.id, task);

  if (task.source === "telegram") {
    void sendTelegramTaskUpdate(task, "revise", { logger: console }).catch(() => {});
  }

  if (BRIDGE_MODE === "real") {
    await runRealTask(task, tasks);
    pushLog(task, "task re-submitted to Cursor adapter");
    addHistoryEvent(task, "execution_started", "Revision re-submitted to Cursor adapter");
    task.updatedAt = nowIso();
    tasks.set(task.id, task);
  } else {
    // Keep immediate response in revision_requested stage.
    setTimeout(async () => {
      const current = tasks.get(task.id);
      if (!current) return;
      try {
        await runTask(current, tasks);
      } catch (error) {
        current.status = "failed";
        current.agentStatus = "failed";
        current.lifecycleStage = "failed";
        current.lastAction = "task_failed";
        if (current.latestRevision) {
          current.latestRevision = { ...current.latestRevision, status: "failed" };
        }
        current.updatedAt = nowIso();
        pushLog(current, `Revision run error: ${error.message || "unknown error"}`);
        addHistoryEvent(current, "task_failed", "Revision run failed", {
          error: error.message || "unknown error",
        });
        tasks.set(current.id, current);
      }
    }, 0);
  }
}

async function runAutoControllerReview(task) {
  if (!task || task.status !== "done") return;
  if (task._autoReviewInProgress) return;
  task._autoReviewInProgress = true;

  try {
    const shouldRevise = hasExecutionIssues(task);
    if (!shouldRevise) {
      applyControllerReviewDecision(
        task,
        "approve",
        "Auto review approved successful result",
        "No further action"
      );
      pushLog(task, "auto review: approved");
      task.updatedAt = nowIso();
      tasks.set(task.id, task);
      return;
    }

    pushLog(task, "auto review: revise triggered");
    task._suppressTelegramReviseFromController = true;
    applyControllerReviewDecision(
      task,
      "revise",
      "Auto review detected errors or empty result",
      "Regenerate and fix task output"
    );
    task._suppressTelegramReviseFromController = false;
    task.updatedAt = nowIso();
    tasks.set(task.id, task);
    await requestRevisionForTask(
      task,
      "Auto review detected errors or empty result",
      "Fix errors and provide non-empty result.summary/changedFiles/checks",
      "controller"
    );
  } finally {
    task._autoReviewPending = false;
    task._autoReviewInProgress = false;
    tasks.set(task.id, task);
  }
}

// GET /
// Local web panel for running and monitoring bridge tasks.
app.get("/", (_req, res) => {
  return res.sendFile(path.join(__dirname, "public", "index.html"));
});

// POST /mcp
// Main MCP entry point for remote ChatGPT integration.
app.post("/mcp", (req, res) => {
  const payload = req.body || {};

  return res.json({
    ok: true,
    service: "automation-bridge",
    mcp: true,
    mode: BRIDGE_MODE,
    timestamp: nowIso(),
    received: payload,
  });
});

// POST /tasks
// Creates a task in "queued", then auto-moves it to "running".
app.post("/tasks", async (req, res) => {
  const parsed = normalizeTaskInput(req.body);
  if (parsed.error) {
    return res.status(400).json({ error: parsed.error });
  }

  const task = createBaseTaskFromParsed(parsed, { sourceLabel: "api", source: "manual" });

  if (BRIDGE_MODE === "mock") {
    // Keep create response in "created" stage, then start mock run asynchronously.
    setTimeout(async () => {
      const current = tasks.get(task.id);
      if (!current) return;
      await startTaskWithRunner(current, "Task runner failed at create");
    }, 0);
  } else {
    const startResult = await startTaskWithRunner(task, "Task runner failed at create");
    if (!startResult.ok) {
      return res.status(500).json({
        error: "Failed to start task via task runner",
        task: sanitizeTask(task),
      });
    }
  }

  return res.status(201).json(sanitizeTask(task));
});

// POST /tasks/preview
// Builds title/prompt from task payload without creating a task.
app.post("/tasks/preview", (req, res) => {
  const parsed = normalizeTaskInput(req.body);
  if (parsed.error) {
    return res.status(400).json({ error: parsed.error });
  }

  return res.json({
    generatedTitle: parsed.generatedTitle,
    generatedPrompt: parsed.generatedPrompt,
    normalizedTask: parsed.normalizedTask,
  });
});

// GET /run
// Browser-friendly trigger: creates task, auto-plans, executes, returns compact JSON.
app.get("/run", async (req, res) => {
  const text = typeof req.query.text === "string" ? req.query.text.trim() : "";
  if (!text) {
    return res.status(400).json({
      ok: false,
      error: "Query parameter 'text' is required",
      example: "/run?text=добавь%20историю%20смет",
    });
  }

  const quickRun = await runQuickTaskFromText(text, {
    sourceLabel: "/run endpoint",
    source: "web",
    triggerLog: "run endpoint triggered",
    planEventMessage: "Auto-plan generated by /run endpoint",
    executionEventMessage: "Execution started from /run endpoint",
  });
  if (!quickRun.ok || !quickRun.task) {
    return res.status(quickRun.statusCode || 400).json({
      ok: false,
      error: quickRun.error || "Failed to run quick task",
    });
  }
  const task = quickRun.task;

  return res.json({
    ok: true,
    taskId: task.id,
    status: task.status,
    summary: buildTaskSummary(task),
    summaryUrl: `/tasks/${encodeURIComponent(task.id)}/summary`,
  });
});

// GET /tasks
// Returns all tasks sorted by creation time (newest first).
app.get("/tasks", (_req, res) => {
  const { status, reviewStatus, archived, lifecycleStage } = _req.query || {};

  if (lifecycleStage && !ALLOWED_LIFECYCLE_STAGES.has(String(lifecycleStage))) {
    return res.status(400).json({
      error:
        "Invalid lifecycleStage. Allowed: created, planned, waiting_user, ready, executing, reported, under_review, revision_requested, completed, failed",
    });
  }

  const list = Array.from(tasks.values())
    .filter((task) => {
      if (status && task.status !== status) return false;
      if (reviewStatus && task.reviewStatus !== reviewStatus) return false;
      if (lifecycleStage && task.lifecycleStage !== lifecycleStage) return false;

      if (archived !== undefined) {
        const wanted =
          String(archived).toLowerCase() === "true" || String(archived) === "1";
        if (Boolean(task.archived) !== wanted) return false;
      }

      return true;
    })
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .map(sanitizeTask);

  return res.json(list);
});

// GET /tasks/:id
// Returns full task state.
app.get("/tasks/:id", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }
  return res.json(sanitizeTask(task));
});

// POST /task-result
// Simplified callback for local watcher / external agent (taskId + status + payload).
app.post("/task-result", (req, res) => {
  const body = req.body || {};
  const taskId = typeof body.taskId === "string" ? body.taskId.trim() : "";
  if (!taskId) {
    return res.status(400).json({ ok: false, error: "taskId is required" });
  }
  const task = tasks.get(taskId);
  if (!task) {
    return res.status(404).json({ ok: false, error: "Task not found" });
  }

  const statusRaw = String(body.status || "").toLowerCase();
  const isError = statusRaw === "error" || statusRaw === "failed";
  const isDone = statusRaw === "done" || statusRaw === "success";
  if (!isError && !isDone) {
    return res.status(400).json({ ok: false, error: 'status must be "done" or "error"' });
  }

  const summary = typeof body.summary === "string" ? body.summary : "";
  const changedFiles = Array.isArray(body.changedFiles)
    ? body.changedFiles.filter((f) => typeof f === "string")
    : [];
  const checks = Array.isArray(body.checks)
    ? body.checks.filter((f) => typeof f === "string")
    : [];
  const notes = Array.isArray(body.notes) ? body.notes.filter((f) => typeof f === "string") : [];

  const logs = body.logs;
  if (Array.isArray(logs)) {
    for (const item of logs) {
      if (typeof item === "string" && item.trim()) {
        pushLog(task, item);
      } else if (item && typeof item.message === "string" && item.message.trim()) {
        pushLog(task, item.message);
      }
    }
  }

  if (isError) {
    const errText =
      typeof body.error === "string" && body.error.trim()
        ? body.error.trim()
        : "Task error";
    task.status = "failed";
    task.agentStatus = "failed";
    task.lifecycleStage = "failed";
    task.lastAction = "task_failed";
    if (task.latestRevision) {
      task.latestRevision = { ...task.latestRevision, status: "failed" };
    }
    pushLog(task, errText);
    addHistoryEvent(task, "task_failed", "task-result: failed", { error: errText });
    task._autoReviewPending = false;
  } else {
    task.status = "done";
    task.agentStatus = "finished";
    task.lifecycleStage = "reported";
    task.lastAction = "task_completed";
    if (task.latestRevision) {
      task.latestRevision = { ...task.latestRevision, status: "done" };
    }
    task.result = {
      summary:
        summary ||
        `Completed for goal: ${String(task.goal || task.title || taskId).slice(0, 200)}`,
      changedFiles,
      checks,
      notes,
    };
    addHistoryEvent(task, "task_completed", "task-result: done");
    task._autoReviewPending = true;
  }

  task.updatedAt = nowIso();
  tasks.set(task.id, task);
  void tryNotifyTelegramExecutionOutcome(tasks.get(task.id)).catch(() => {});
  return res.json({ ok: true, task: sanitizeTask(task) });
});

// POST /tasks/:id/cursor-webhook
// Simulates updates from Cursor side (status/result/log append).
app.post("/tasks/:id/cursor-webhook", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  const {
    externalTaskId,
    agentStatus,
    status,
    result,
    report,
    logMessage,
    reviewStatus,
  } = req.body || {};

  if (externalTaskId !== undefined) {
    task.externalTaskId = externalTaskId;
  }

  if (agentStatus !== undefined) {
    if (!ALLOWED_AGENT_STATUSES.has(agentStatus)) {
      return res.status(400).json({
        error:
          "Invalid agentStatus. Allowed: pending, submitted, running, finished, failed",
      });
    }
    task.agentStatus = agentStatus;
    if (task.latestRevision) {
      if (agentStatus === "submitted") {
        task.latestRevision = { ...task.latestRevision, status: "submitted" };
      } else if (agentStatus === "running") {
        task.latestRevision = { ...task.latestRevision, status: "running" };
      } else if (agentStatus === "finished") {
        task.latestRevision = { ...task.latestRevision, status: "done" };
      } else if (agentStatus === "failed") {
        task.latestRevision = { ...task.latestRevision, status: "failed" };
      }
    }
  }

  if (status !== undefined) {
    if (!ALLOWED_STATUSES.has(status)) {
      return res.status(400).json({
        error: "Invalid status. Allowed: queued, running, done, failed",
      });
    }
    task.status = status;
    if (task.latestRevision) {
      task.latestRevision = { ...task.latestRevision, status };
    }
    if (status === "running") {
      task.lifecycleStage = "executing";
      task.lastAction = "cursor_report_received";
    } else if (status === "done") {
      task.lifecycleStage = "reported";
      task.lastAction = "cursor_report_received";
      addHistoryEvent(task, "task_completed", "Task marked done by Cursor webhook");
      task._autoReviewPending = true;
    } else if (status === "failed") {
      task.lifecycleStage = "failed";
      task.lastAction = "cursor_report_received";
      addHistoryEvent(task, "task_failed", "Task marked failed by Cursor webhook");
    }
  }

  if (reviewStatus !== undefined) {
    if (!ALLOWED_REVIEW_STATUSES.has(reviewStatus)) {
      return res.status(400).json({
        error: "Invalid reviewStatus. Allowed: pending, approved, rejected",
      });
    }
    task.reviewStatus = reviewStatus;
  }

  if (result !== undefined) {
    task.result = result;
  }

  if (report !== undefined) {
    if (!isPlainObject(report)) {
      return res.status(400).json({ error: "report must be an object" });
    }
    task.report = report;
  }

  if (logMessage !== undefined) {
    pushLog(task, logMessage);
  }

  addHistoryEvent(task, "cursor_report_received", "Cursor webhook received", {
    status: task.status,
    agentStatus: task.agentStatus,
  });

  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  return res.json(sanitizeTask(task));
});

// POST /tasks/:id/controller-review
// Saves decision from controller (ChatGPT) side.
app.post("/tasks/:id/controller-review", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  const { decision, note, nextAction } = req.body || {};

  if (!["approve", "revise", "reject"].includes(decision)) {
    return res.status(400).json({
      error: "decision must be one of: approve, revise, reject",
    });
  }

  applyControllerReviewDecision(task, decision, note, nextAction);
  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  return res.json(sanitizeTask(task));
});

// GET /tasks/:id/summary
// Returns compact task summary for ChatGPT controller.
app.get("/tasks/:id/summary", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  return res.json(buildTaskSummary(task));
});

// GET /tasks/:id/timeline
// Returns lifecycle stage and full task history.
app.get("/tasks/:id/timeline", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  return res.json({
    id: task.id,
    goal: task.goal,
    lifecycleStage: task.lifecycleStage,
    history: Array.isArray(task.history) ? task.history : [],
  });
});

// POST /tasks/:id/revise
// Requests a revision and re-runs the same task instance.
app.post("/tasks/:id/revise", async (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  const { reason, instructions, requestedBy } = req.body || {};
  if (typeof reason !== "string" || !reason.trim()) {
    return res.status(400).json({ error: "reason is required and must be a non-empty string" });
  }
  if (typeof instructions !== "string" || !instructions.trim()) {
    return res
      .status(400)
      .json({ error: "instructions is required and must be a non-empty string" });
  }

  try {
    await requestRevisionForTask(task, reason, instructions, requestedBy);
  } catch (error) {
    task.status = "failed";
    task.agentStatus = "failed";
    task.lifecycleStage = "failed";
    task.lastAction = "task_failed";
    if (task.latestRevision) {
      task.latestRevision = { ...task.latestRevision, status: "failed" };
    }
    task.updatedAt = nowIso();
    pushLog(task, `Revision run error: ${error.message || "unknown error"}`);
    addHistoryEvent(task, "task_failed", "Revision run failed", {
      error: error.message || "unknown error",
    });
    tasks.set(task.id, task);
    return res.status(500).json({
      error: "Failed to run revision via task runner",
      task: sanitizeTask(task),
    });
  }

  return res.json(sanitizeTask(task));
});

// POST /tasks/:id/plan
// Stores plan and preparation metadata from ChatGPT.
app.post("/tasks/:id/plan", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  const { plan, risks, needsUserInput, questions } = req.body || {};

  if (!Array.isArray(plan) || !plan.every((item) => typeof item === "string")) {
    return res.status(400).json({ error: "plan must be an array of strings" });
  }
  if (risks !== undefined && (!Array.isArray(risks) || !risks.every((item) => typeof item === "string"))) {
    return res.status(400).json({ error: "risks must be an array of strings" });
  }
  if (questions !== undefined && (!Array.isArray(questions) || !questions.every((item) => typeof item === "string"))) {
    return res.status(400).json({ error: "questions must be an array of strings" });
  }
  if (needsUserInput !== undefined && typeof needsUserInput !== "boolean") {
    return res.status(400).json({ error: "needsUserInput must be boolean" });
  }

  task.plan = plan;
  task.risks = risks || [];
  task.questions = questions || [];
  task.needsUserInput = Boolean(needsUserInput);
  pushLog(task, "plan received");
  addHistoryEvent(task, "plan_received", "Execution plan received");
  task.lastAction = "plan_received";

  if (!task.needsUserInput) {
    task.agentStatus = "submitted";
    task.lifecycleStage = "ready";
    pushLog(task, "ready for execution");
  } else {
    task.lifecycleStage = "waiting_user";
  }

  task.updatedAt = nowIso();
  tasks.set(task.id, task);
  return res.json(sanitizeTask(task));
});

// POST /tasks/:id/execute
// Moves task into execution state if planning is complete.
app.post("/tasks/:id/execute", async (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  if (!Array.isArray(task.plan) || task.plan.length === 0) {
    return res.status(400).json({ error: "Task has no plan. Submit /plan first" });
  }

  if (task.needsUserInput) {
    return res.status(400).json({ error: "Task waits for user input before execution" });
  }

  task.status = "running";
  task.lifecycleStage = "executing";
  task.lastAction = "execution_started";
  pushLog(task, "execution started");
  addHistoryEvent(task, "execution_started", "Execution started");
  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  try {
    await runTask(task, tasks);
  } catch (error) {
    task.status = "failed";
    task.agentStatus = "failed";
    task.lifecycleStage = "failed";
    task.lastAction = "task_failed";
    task.updatedAt = nowIso();
    pushLog(task, `Task runner error: ${error.message || "unknown error"}`);
    addHistoryEvent(task, "task_failed", "Execution failed in task runner", {
      error: error.message || "unknown error",
    });
    tasks.set(task.id, task);
    return res.status(500).json({
      error: "Failed to execute task via task runner",
      task: sanitizeTask(task),
    });
  }

  return res.json(sanitizeTask(task));
});

// POST /tasks/:id/user-response
// Stores user answer and unblocks execution.
app.post("/tasks/:id/user-response", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  const { answer } = req.body || {};
  if (typeof answer !== "string" || !answer.trim()) {
    return res.status(400).json({ error: "answer is required and must be a non-empty string" });
  }

  pushLog(task, `user answer: ${answer.trim()}`);
  task.needsUserInput = false;
  task.agentStatus = "submitted";
  task.lifecycleStage = "ready";
  task.lastAction = "user_input_received";
  pushLog(task, "user input received");
  addHistoryEvent(task, "user_input_received", "User response received", {
    answer: answer.trim(),
  });
  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  return res.json(sanitizeTask(task));
});

// POST /tasks/:id/review
// Applies review decision for a task.
app.post("/tasks/:id/review", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  const { decision, note } = req.body || {};
  if (decision !== "approve" && decision !== "reject") {
    return res.status(400).json({
      error: "decision must be either 'approve' or 'reject'",
    });
  }

  task.reviewStatus = decision === "approve" ? "approved" : "rejected";
  pushLog(task, `Review decision: ${decision}${note ? ` | note: ${note}` : ""}`);
  task.updatedAt = nowIso();
  tasks.set(task.id, task);

  return res.json(sanitizeTask(task));
});

// POST /tasks/:id/archive
// Marks task as archived.
app.post("/tasks/:id/archive", (req, res) => {
  const task = tasks.get(req.params.id);
  if (!task) {
    return res.status(404).json({ error: "Task not found" });
  }

  task.archived = true;
  task.lastAction = "archived";
  task.updatedAt = nowIso();
  addHistoryEvent(task, "task_archived", "Task archived");
  tasks.set(task.id, task);

  return res.json(sanitizeTask(task));
});

// GET /dashboard
// Returns compact orchestration metrics.
app.get("/dashboard", (_req, res) => {
  const list = Array.from(tasks.values());
  const byStatus = {};
  const byLifecycleStage = {};
  const byReviewStatus = {};
  let pendingUserInput = 0;
  let needsReview = 0;
  let activeRevisions = 0;

  list.forEach((task) => {
    byStatus[task.status] = (byStatus[task.status] || 0) + 1;
    byLifecycleStage[task.lifecycleStage] =
      (byLifecycleStage[task.lifecycleStage] || 0) + 1;
    byReviewStatus[task.reviewStatus] = (byReviewStatus[task.reviewStatus] || 0) + 1;

    if (task.needsUserInput) pendingUserInput += 1;
    if (task.lifecycleStage === "reported" || task.lifecycleStage === "under_review") {
      needsReview += 1;
    }
    if (task.latestRevision && task.latestRevision.status !== "done") {
      activeRevisions += 1;
    }
  });

  return res.json({
    totalTasks: list.length,
    byStatus,
    byLifecycleStage,
    byReviewStatus,
    pendingUserInput,
    needsReview,
    activeRevisions,
  });
});

// Auto controller-review processor:
// runs in background and reacts to completed tasks flagged by runner/webhook.
setInterval(async () => {
  for (const task of tasks.values()) {
    if (!task || task._autoReviewPending !== true) continue;
    if (task.status !== "done") {
      task._autoReviewPending = false;
      tasks.set(task.id, task);
      continue;
    }
    try {
      await runAutoControllerReview(task);
    } catch (error) {
      task._autoReviewPending = false;
      task._autoReviewInProgress = false;
      task.updatedAt = nowIso();
      pushLog(task, `auto review error: ${error.message || "unknown error"}`);
      addHistoryEvent(task, "task_failed", "Auto review processing failed", {
        error: error.message || "unknown error",
      });
      tasks.set(task.id, task);
    }
  }
}, 1000);

setInterval(() => {
  for (const task of tasks.values()) {
    if (!task || task.source !== "telegram") continue;
    void tryNotifyTelegramExecutionOutcome(task).catch(() => {});
  }
}, 1100);

app.get("/health", (_req, res) => {
  res.json({
    ok: true,
    mode: BRIDGE_MODE,
    totalTasks: tasks.size,
    uptimeSeconds: Math.floor(process.uptime()),
  });
});

app.get("/healthz", (_req, res) => {
  res.json({
    ok: true,
    service: "automation-bridge",
    mcp: true,
  });
});

// Return JSON for malformed JSON bodies instead of HTML.
app.use((err, _req, res, next) => {
  if (err && err.type === "entity.parse.failed") {
    return res.status(400).json({
      ok: false,
      error: "Invalid JSON body",
    });
  }
  return next(err);
});

(async () => {
  try {
    await tryAutoFillTelegramChatIdFromUpdates();
  } catch (error) {
    console.log(`telegram autofill skipped: ${error.message || "unknown error"}`);
  }

  app.listen(PORT, () => {
    console.log("Automation bridge restarted");
    console.log(`automation-bridge running on http://localhost:${PORT}`);
    reloadProcessEnvFromFile();
    const { token, chatId } = getTelegramEnv();
    const hasToken = Boolean(token);
    const hasChatId = Boolean(chatId);
    const tgPolling = hasToken;
    console.log(`TELEGRAM_BOT_TOKEN present: ${hasToken ? "yes" : "no"}`);
    console.log(`TELEGRAM_ALLOWED_CHAT_ID present: ${hasChatId ? "yes" : "no"}`);
    console.log(`telegram polling (minimal bot): ${tgPolling ? "yes" : "no"}`);
    syncTelegramDebugEnv({
      telegramEnabled: tgPolling,
      allowedChatId: chatId || null,
    });
    console.log(
      `[telegram] startup: polling=${tgPolling} has_TELEGRAM_BOT_TOKEN=${hasToken} has_TELEGRAM_ALLOWED_CHAT_ID=${hasChatId}`
    );
    if (tgPolling) {
      console.log("[telegram] telegramBot launch mode: long polling (echo «Бот работает»)");
    } else {
      console.log("[telegram] telegramBot: not started (missing TELEGRAM_BOT_TOKEN)");
    }
    startTelegramRuntimeFromProcessEnv();
  });
})();
